version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    container_name: url_shortener_redis
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes

volumes:
  redis_data: